export const useShowMenuButtonState = () => useState('showMenuButton', () => true)
export const useShowMenuState = () => useState('showMenu', () => false)
export const useMenuAnimationState = () => useState('menuAnimation', () => true)
export const useBgBlackState = () => useState('bgBlack', () => false)
// export const useNavigationAnimationState = () => useState('navigationAnimation', () => false)
